name: build

on:
  push:
  schedule:
    - cron: '0 23 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up multiarch/qemu-user-static
        run: |
          docker run --rm --privileged multiarch/qemu-user-static:register --reset
      - uses: docker://multiarch/ubuntu-core:arm64-bionic
        with:
          args: >
            bash -c
            "apt update &&
            apt install build-essential dpkg-dev make gcc git python3 cmake -y &&
            cd /github/workspace &&
            git clone https://github.com/ptitSeb/box64.git &&
            cd ./box64 &&
            mkdir build &&
            cd build &&
            cmake .. -DCMAKE_BUILD_TYPE=RelWithDebInfo -DARM_DYNAREC=1 &&
            make &&
            make package &&
            rm -rf ../../box64*.deb &&
            mv ./*.deb ../../ &&
            cd ../../ &&
            rm -rf ./box64/"
      - uses: docker://multiarch/ubuntu-core:armhf-bionic
        with:
          args: >
            bash -c
            "apt update &&
            apt install build-essential dpkg-dev make gcc git python3 cmake -y &&
            cd /github/workspace &&
            git clone https://github.com/ptitSeb/box86.git &&
            cd ./box86 &&
            mkdir build &&
            cd build &&
            cmake .. -DCMAKE_BUILD_TYPE=RelWithDebInfo -DARM_DYNAREC=1 &&
            make &&
            make package &&
            rm -rf ../../box86*.deb &&
            mv ./*.deb ../../ &&
            cd ../../ &&
            rm -rf ./box86/"
            
      - name: Upload
        run: |
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git add .
          git commit -m "Upload box64 and box64 for $(printf '%(%Y-%m-%d)T\n' -1)" 
          git push
