name: build

on:
  schedule:
    - cron: '0 1 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up multiarch/qemu-user-static
        run: |
          docker run --rm --privileged multiarch/qemu-user-static:register --reset
      - uses: docker://multiarch/ubuntu-core:armhf-bionic
        with:
          args: >
            bash -c
            "apt update &&
            apt install build-essential dpkg-dev make gcc git python3 cmake -y &&
            cd /github/workspace &&
            echo "Building for rpi4" &&
            git clone https://github.com/ptitSeb/box86.git &&
            cd ./box86 &&
            mkdir build &&
            cd build &&
            cmake .. -DCMAKE_BUILD_TYPE=RelWithDebInfo -DRPI4=1 &&
            make -j8 &&
            make package &&
            rm -rf ../../box86*.deb &&
            mkdir -p ../../$(printf '%(%Y-%m-%d)T\n' -1) &&
            mkdir -p ../../$(printf '%(%Y-%m-%d)T\n' -1)/rpi4 &&
            mv ./*.deb ../../$(printf '%(%Y-%m-%d)T\n' -1)/rpi4/ &&
            cd ../../ &&
            rm -rf ./box86/ &&
            echo "Building for pandora" &&
            git clone https://github.com/ptitSeb/box86.git &&
            cd ./box86 &&
            mkdir build &&
            cd build &&
            cmake .. -DCMAKE_BUILD_TYPE=RelWithDebInfo -DPANDORA=1 &&
            make -j8 &&
            make package &&
            rm -rf ../../box86*.deb &&
            mkdir -p ../../$(printf '%(%Y-%m-%d)T\n' -1) &&
            mkdir -p ../../$(printf '%(%Y-%m-%d)T\n' -1)/pandora &&
            mv ./*.deb ../../$(printf '%(%Y-%m-%d)T\n' -1)/pandora/ &&
            cd ../../ &&
            rm -rf ./box86/"
            
      - name: Upload
        run: |
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git add .
          git commit -m "Upload box86 rpi for $(printf '%(%Y-%m-%d)T\n' -1)" 
          git push
