name: build

on:
  schedule:
    - cron: '0 1 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up multiarch/qemu-user-static
        run: |
          docker run --rm --privileged multiarch/qemu-user-static:register --reset
      - uses: docker://multiarch/ubuntu-core:armhf-bionic
        with:
          args: >
            bash -c
            "pwd && ls && pwd"
            
      - name: Upload
        run: |
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git add .
          git commit -m "Upload box86 for $(printf '%(%Y-%m-%d)T\n' -1)" 
          git push
